version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 17vasant13
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpvasant
      MYSQL_PASSWORD: 17vasant13

  mywordpress:
    depends_on:
    - db
    image: wordpress:latest
    ports:
    - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpvasant
      WORDPRESS_DB_PASSWORD: 17vasant13

volumes:
  db_data:

